// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZU4793XA-mfxinpRjVRKeSKEg-czwN7A',
    appId: '1:610185294312:web:16c5f8066f579b0a44745d',
    messagingSenderId: '610185294312',
    projectId: 'flutter-begin-7b0d6',
    authDomain: 'flutter-begin-7b0d6.firebaseapp.com',
    storageBucket: 'flutter-begin-7b0d6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlDTONeT-tF0LrZ8MTGDIoGezyLi5v0Qg',
    appId: '1:610185294312:android:31cbe68118c2185f44745d',
    messagingSenderId: '610185294312',
    projectId: 'flutter-begin-7b0d6',
    storageBucket: 'flutter-begin-7b0d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGagLdjRxA5F8h0sz9h91fVS_gpAm_Gps',
    appId: '1:610185294312:ios:6ad20f0cf260549f44745d',
    messagingSenderId: '610185294312',
    projectId: 'flutter-begin-7b0d6',
    storageBucket: 'flutter-begin-7b0d6.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );
}
